name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - run: npm ci
      - run: npx cap sync android
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - uses: android-actions/setup-android@v3
      - run: chmod +x android/gradlew
      - run: ./gradlew assembleDebug
        working-directory: android
      - uses: actions/upload-artifact@v4
        with:
          name: NicePlayer-ARM64
          path: android/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
      - uses: actions/upload-artifact@v4
        with:
          name: NicePlayer-ARM32
          path: android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
